// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFr1P1bu11KCLCvBS2Yym_z4M9SfM-H00',
    appId: '1:1035949194269:web:f286b64d1e1c6b50a29af4',
    messagingSenderId: '1035949194269',
    projectId: 'movies-app-837c1',
    authDomain: 'movies-app-837c1.firebaseapp.com',
    storageBucket: 'movies-app-837c1.appspot.com',
    measurementId: 'G-MGK6NH6PME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0F9j2RZ4-bub4T7eQKFMYd7eZl5xX0nM',
    appId: '1:1035949194269:android:eded49b6ee897165a29af4',
    messagingSenderId: '1035949194269',
    projectId: 'movies-app-837c1',
    storageBucket: 'movies-app-837c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtUucjlKihV9pckgfRD64Txk-GT9ouRo',
    appId: '1:1035949194269:ios:57e21c200627bfdca29af4',
    messagingSenderId: '1035949194269',
    projectId: 'movies-app-837c1',
    storageBucket: 'movies-app-837c1.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWtUucjlKihV9pckgfRD64Txk-GT9ouRo',
    appId: '1:1035949194269:ios:57e21c200627bfdca29af4',
    messagingSenderId: '1035949194269',
    projectId: 'movies-app-837c1',
    storageBucket: 'movies-app-837c1.appspot.com',
    iosBundleId: 'com.example.moviesapp',
  );
}
